### ISSUE TITLE
timeout sur getsession lock

### ISSUE THREAD

**Issue by goudal-emmk** [UGAsapiens/moodle-mod-automultiplechoice#2]
Lors de la génération des copies annotées on se retrouve avec un message généré par un time out sur dml_sessionwait_exception(); dans get_session_lock.

La génération peut-être très longue, nous avons à gérer 65 copies et la durée de génération des annotation est de quelques minutes.

**Comment by mytskine** [comment]
Je ne pense pas que le module AMC soit en cause. Les outils AMC sont effectivement lents et peuvent s'exécuter pendant plusieurs minutes. Mais si j'en crois un rapide coup d'œil dans le code de Moodle cette erreur ne survient que si on stocke les sessions utilisateurs dans la base de données. Donc ce système (en plus d'être inadapté sur les sites à forte fréquentation) n'est pas fiable pour les requêtes longues.
Essayez de stocker les sessions en fichiers (mode natif PHP).

**Comment by goudal-emmk** [comment]
Bonjour,

Ok... 

Un peu de doc sur le sujet serait bien venu non ?

f.g.

**Comment by mytskine** [comment]
Pour être clair, je ne sais pas pourquoi l'exception se produit, mais rien n'indique que le module soit en faute, le bug semble venir de la gestion des sessions de Moodle.

Sessions DB pour Moodle : https://docs.moodle.org/28/en/Session_handling#Database

> The performance is relatively low, it is not recommended for large sites.

Pour plus de détails sur les performances des sessions en DB :
- http://pages.cs.wisc.edu/~bpkroth/cs764/bpkroth_cs764_project_report.pdf
- https://moodle.org/mod/forum/discuss.php?d=267407
- https://moodle.org/mod/forum/discuss.php?d=227811

**Comment by goudal-emmk** [comment]
Oui, j'ai bien compris, ce que je disais c'est juste de signaler dans la doc du module que vu la longueur des traitement, il n'est pas conseillé d'utiliser les sessions sur base de donnée..

Une chose qui me chiffonne avec ces traitements et que si on veut récupérer une deuxième fois les copies corriger il semble qu'il faille relancer le traitement.

f.g.
